### ISSUE TITLE
Example on how to disable verify_directories?

### ISSUE THREAD

**Issue by marksteele** [uwiger/setup#21]
I've tried setting this in the regular env (via sys.config), to no avail. Do you have an example on how to prevent setup from creating folders when it's not being used for managing them? (my specific use case is using exometer_core)

**Comment by uwiger** [comment]
You may need to upgrade to a newer exometer_core

See https://github.com/Feuerlabs/exometer_core/issues/58

**Comment by tolbrino** [comment]
I guess this is not an issue anymore.
