### ISSUE TITLE
Missing top supervisor?

### ISSUE THREAD

**Issue by arnvald** [uwiger/setup#22]
Hi Ulf,

I guess my question my actually not be an issue with `setup`, but I have a problem that I can't solve and it's somehow related to this library. I thought maybe you'll have some clue on why it happens.

I'm using Elixir and its `Exrm` library for generate a new release for my app and upgrade it on the fly. One of the requirements to make it happen is that all applications have a top-level supervisor. This is to ensure that they can handle failures probably. The issue is better described here:  https://github.com/bitwalker/exrm/issues/183

When upgrading I get the message `release_handler: cannot find top supervisor for application setup`

Do you maybe know if this is an issue with `setup` and can be fixed? Or maybe it's more `Exrm` problem?

**Comment by tolbrino** [comment]
Hmm, weird that I didn't run into this issue although I already used the combination of Elixir, setup and exrm. I will double-check that again.

**Comment by arnvald** [comment]
Hi @tolbrino,

thanks for your response! I confirm that once I added supervisor (I don't know Erlang at all, so I did it in a very primitive way) to `setup.erl` and started it instead of running `proc_lib:start_link` directly, the upgrades started working
