### ISSUE TITLE
License is unclear - MPLv2.0 in LICENSE while ASLv2.0 in sources

### ISSUE THREAD

**Issue by lemenkov** [uwiger/setup#27]
Hello @uwiger!
Could you please clarify licensing. Licensing situation is unclear right now - LICENSE file contains Mozilla Public License Version 2.0 text, but all the source files still have ASL 2.0 in their headers.

**Comment by uwiger** [comment]
License should be ASL 2.0

**Comment by lemenkov** [comment]
Thanks!
