### ISSUE TITLE
stop_when_done = true always triggers timeout

### ISSUE THREAD

**Issue by meike-hecker** [uwiger/setup#29]
In setup_srv:run_setup/0 gen_server call has default timeout of 5 sec. At the end of setup:run_setup/0 in case of stop_when_done=true process sleeps for 5 seconds which leads to a timeout in setup_srv in any case and I guess next line to stop system gracefully will never be called.
My intention to use setup was to do some mnesia table preparation and some other stuff which might take much longer than 5 seconds.
I would do the timeout configurable to allow time consuming setup steps.
https://github.com/meike-hecker/setup/commit/aefeb8ebbcdcc1174b01515ca2aafa4304391532
I am also not sure the sleep really makes sense here.

**Comment by uwiger** [comment]
The timeout error was an unintended consequence of introducing an OTP-style start structure for setup. I've changed it to never time out, unless the user specifies a `run_timeout' value. I've also made the stop delay configurable.

**Comment by meike-hecker** [comment]
perfect, thanks!
