### ISSUE TITLE
setup_gen has option 'outdir' in docs but it is only 'out' in code

### ISSUE THREAD

**Issue by meike-hecker** [uwiger/setup#30]
I would provide a pull request, but I am not sure what is wrong, documentation or code or if you prefer to allow out and outdir
https://github.com/uwiger/setup/blob/master/src/setup_gen.erl#L281
https://github.com/uwiger/setup/blob/master/src/setup_gen.erl#L70
https://github.com/meike-hecker/setup/commit/f16641c1adeb351c76721bfd0dd41fd6f9f1fb9c

**Comment by uwiger** [comment]
Well, the command-line arguments and the config options are sometimes named differently. However, it's unfortunate if they *have to* be named differently. I'll try to make it a little bit more intuitive.

As a general rule, I'd say that any fix should be compatible, if possible, with both the documented and the de-facto behavior. :)

**Comment by meike-hecker** [comment]
Ah, now I see the real issue: the command-line argument 'out' is undocumented ;)

**Comment by meike-hecker** [comment]
I guess changing documentation is enough
